import ipaddress
import json
from pathlib import Path

from . import config

MSI_FILENAME = "IT-Toolkit-Agent.msi"


def _agent_meta() -> dict:
    """Single source of truth for agent version/interval lives in
    Enterprise/agent/agent-version.json; deploy.sh/deploy.ps1 copy it into
    the api build context (Enterprise/api/agent-version.json) before compose
    up, so the container sees /app/agent-version.json (A2)."""
    here = Path(__file__).resolve()
    for root in (here.parents[1], here.parents[2] / "agent"):
        p = root / "agent-version.json"
        if p.exists():
            return json.loads(p.read_text())
    raise RuntimeError("agent-version.json not found (api build context or repo agent/ dir) — version/interval are not hardcoded here.")


AGENT_VERSION = _agent_meta()["agent_version"]
INTERVAL_MINUTES = int(_agent_meta()["interval_minutes"])


def is_ip_literal(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return False


def scheme_for(host: str) -> str:
    """Match deploy.sh: a bare IP is served over plain http (intranet);
    a hostname implies TLS/https via Caddy."""
    return "http" if is_ip_literal(host) else "https"


async def build_agent_json(pool) -> dict:
    """Assemble the company-scoped agent.json from setup answers + live
    feature overrides. This is the config the MSI/install-agent.cmd ships."""
    company = await pool.fetchval("SELECT value FROM settings WHERE key = 'company_name'")
    host = await pool.fetchval("SELECT value FROM settings WHERE key = 'server_host'")

    with open(config.FEATURES_FILE, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)["features"]
    overrides = {r["name"]: r for r in await pool.fetch("SELECT * FROM feature_configs")}

    features = []
    for feat in manifest:
        row = overrides.get(feat["name"])
        features.append({
            "name": feat["name"],
            "script": feat["script"],
            "enabled": row["enabled"] if row else feat.get("default_enabled", True),
            # E4: collectors that need an elevated token are opt-in; the agent
            # skips them unless it is running under the on-demand elevated task.
            "requires_elevation": bool(feat.get("requires_elevation", False)),
        })

    return {
        "company": company,
        # mTLS: agents always talk to the :9443 client-auth port (TLS via the
        # internal CA). enroll_url goes over the MAIN port because Caddy :9443
        # only routes /ingest and /api/commands/* (a fresh agent has no client
        # cert yet to enroll over 9443).
        "endpoint": f"https://{host}:9443/ingest",
        "enroll_url": f"{scheme_for(host)}://{host}/api/agent/enroll",
        "token": config.API_TOKEN,
        "agent_version": AGENT_VERSION,
        "interval_minutes": INTERVAL_MINUTES,
        "features": features,
    }


def build_install_cmd(agent_json: dict, ca_present: bool) -> str:
    """Live-generated installer that drops the company agent.json + ca.crt into
    the agent's runtime config dir after the (generic) MSI install, so the
    per-company values win over the template bundled in the MSI."""
    endpoint = agent_json["endpoint"]
    token = agent_json["token"]
    dest = "%ProgramData%\\ITToolkit-Agent"
    lines = [
        "@echo off",
        "REM IT-Toolkit Agent - company installer (generated by the server)",
        f"REM Company: {agent_json.get('company', '')}",
        f"echo Installing IT-Toolkit Agent for {agent_json.get('company', '')}...",
        'msiexec /i "%~dp0IT-Toolkit-Agent.msi" /qn',
        f'if not exist "{dest}" mkdir "{dest}"',
        'copy /Y "%~dp0agent.json" "%ProgramData%\\ITToolkit-Agent\\agent.json" >nul',
    ]
    if ca_present:
        lines.append('copy /Y "%~dp0ca.crt" "%ProgramData%\\ITToolkit-Agent\\ca.crt" >nul')
    lines += [
        f'reg add "HKLM\\SOFTWARE\\ITToolkit\\Agent" /v EndpointUrl /t REG_SZ /d "{endpoint}" /f >nul',
        f'reg add "HKLM\\SOFTWARE\\ITToolkit\\Agent" /v ApiToken /t REG_SZ /d "{token}" /f >nul',
        'echo Done. The agent will appear in the portal after its first cycle.',
    ]
    return "\r\n".join(lines)


def msi_path() -> Path:
    return config.ARTIFACTS_DIR / MSI_FILENAME


def msi_available() -> bool:
    return msi_path().exists()
