import os
import secrets
from pathlib import Path

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://ittoolkit:change-me@db:5432/ittoolkit")
SERVER_HOST = os.environ.get("SERVER_HOST", "localhost")
PORTAL_DIR = os.environ.get("PORTAL_DIR", "/app/portal")
FEATURES_FILE = os.environ.get("FEATURES_FILE", "/app/features.json")
DATA_DIR = Path(os.environ.get("DATA_DIR", "/data"))
ARTIFACTS_DIR = Path(os.environ.get("ARTIFACTS_DIR", "/artifacts"))

# ---------------------------------------------------------------- command channel (P5)

ALLOW_RUN_SCRIPT = os.environ.get("COMMANDS_RUN_SCRIPT_ALLOWED", "false").lower() in (
    "1", "true", "yes",
)
RUN_SCRIPT_ALLOWLIST = [
    s.strip()
    for s in os.environ.get("RUN_SCRIPT_ALLOWLIST", "").split(",")
    if s.strip()
]

# ---------------------------------------------------------------- alerts (P6)

ALERT_EVAL_MINUTES = int(os.environ.get("ALERT_EVAL_MINUTES", "1"))

# SMTP email delivery for alerts (P6.1). Emails are only sent when SMTP_HOST
# is set; the rest are optional (STARTTLS default on, port 587).
SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_FROM = os.environ.get("SMTP_FROM", "")
SMTP_TO = [
    s.strip()
    for s in os.environ.get("SMTP_TO", "").split(",")
    if s.strip()
]
SMTP_STARTTLS = os.environ.get("SMTP_STARTTLS", "true").lower() in ("1", "true", "yes")

# ---------------------------------------------------------------- API token

_PLACEHOLDERS = {"", "change-me", "change-me-random-token", "changeme"}


def _resolve_secret(env_name: str, filename: str) -> str:
    """Use the env var if it's a real value; else read-or-create a persisted
    random secret under DATA_DIR so it survives restarts."""
    val = os.environ.get(env_name, "")
    if val not in _PLACEHOLDERS:
        return val
    f = DATA_DIR / filename
    if f.exists():
        tok = f.read_text(encoding="utf-8").strip()
        if tok:
            return tok
    tok = secrets.token_urlsafe(32)
    try:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        f.write_text(tok, encoding="utf-8")
    except OSError:
        pass
    return tok


def _resolve_token() -> tuple[str, bool]:
    """Return (token, was_autogenerated).

    Uses API_TOKEN when it is a real value. Otherwise auto-generates a random
    token, persists it to DATA_DIR/api_token so it survives restarts, and flags
    it so startup can print it for the operator.
    """
    provided = os.environ.get("API_TOKEN", "")
    if provided not in _PLACEHOLDERS:
        return provided, False

    token_file = DATA_DIR / "api_token"
    if token_file.exists():
        token = token_file.read_text(encoding="utf-8").strip()
        if token:
            return token, False

    token = secrets.token_urlsafe(32)
    try:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        token_file.write_text(token, encoding="utf-8")
    except OSError:
        pass  # volume unavailable -> token still valid for this process lifetime
    return token, True


API_TOKEN, API_TOKEN_AUTOGENERATED = _resolve_token()
SESSION_SECRET = _resolve_secret("SESSION_SECRET", "session_secret")
