import os
import secrets
from pathlib import Path

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://ittoolkit:change-me@db:5432/ittoolkit")
SERVER_HOST = os.environ.get("SERVER_HOST", "localhost")
PORTAL_DIR = os.environ.get("PORTAL_DIR", "/app/portal")
FEATURES_FILE = os.environ.get("FEATURES_FILE", "/app/features.json")

# ---------------------------------------------------------------- API token

_PLACEHOLDERS = {"", "change-me", "change-me-random-token", "changeme"}


def _resolve_token() -> tuple[str, bool]:
    """Return (token, was_autogenerated).

    Uses API_TOKEN when it is a real value. Otherwise auto-generates a random
    token, persists it to API_TOKEN_FILE (a mounted volume) so it survives
    restarts, and flags it so startup can print it for the operator.
    """
    provided = os.environ.get("API_TOKEN", "")
    if provided not in _PLACEHOLDERS:
        return provided, False

    token_file = Path(os.environ.get("API_TOKEN_FILE", "/data/api_token"))
    if token_file.exists():
        token = token_file.read_text(encoding="utf-8").strip()
        if token:
            return token, False

    token = secrets.token_urlsafe(32)
    try:
        token_file.parent.mkdir(parents=True, exist_ok=True)
        token_file.write_text(token, encoding="utf-8")
    except OSError:
        pass  # volume unavailable -> token still valid for this process lifetime
    return token, True


API_TOKEN, API_TOKEN_AUTOGENERATED = _resolve_token()
