import hashlib
import hmac
import io
import json
import secrets
import uuid
import asyncio
import csv
from pathlib import Path

import asyncpg
from fastapi import FastAPI, Depends, Header, HTTPException, Request, Response
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import auth, bundle, certs, config, db, rules

app = FastAPI(title="IT-Toolkit Enterprise", version="1.0.0")

ROLES = ("admin", "operation", "monitoring")


# ---------------------------------------------------------------- deps

def require_token(authorization: str = Header(default="")) -> None:
    """Agent bearer token (used by /ingest)."""
    expected = f"Bearer {config.API_TOKEN}"
    if not hmac.compare_digest(authorization.strip(), expected):
        raise HTTPException(status_code=401, detail="Invalid or missing token")


async def require_setup_done() -> None:
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    if not done:
        raise HTTPException(status_code=428, detail="Setup required")


async def require_session(request: Request) -> dict:
    token = request.cookies.get(auth.SESSION_COOKIE, "")
    user_id = auth.verify_session(token)
    if user_id is None:
        raise HTTPException(status_code=401, detail="Not logged in")
    pool = await db.connect()
    user = await pool.fetchrow(
        "SELECT id, username, role, active FROM users WHERE id = $1 AND active = TRUE",
        user_id,
    )
    if user is None:
        raise HTTPException(status_code=401, detail="Not logged in")
    return dict(user)


def require_role(*roles: str):
    """Dependency factory: like require_session, but also enforces a role."""

    async def _dep(user: dict = Depends(require_session)) -> dict:
        if user["role"] not in roles:
            raise HTTPException(status_code=403, detail="Forbidden for this role")
        return user

    return _dep


async def get_agent_id(pool, hostname: str) -> int:
    row = await pool.fetchrow(
        "INSERT INTO agents (hostname) VALUES ($1) "
        "ON CONFLICT (hostname) DO UPDATE SET last_seen = now() RETURNING id",
        hostname,
    )
    return row["id"]


# ---------------------------------------------------------------- models

class EventItem(BaseModel):
    kind: str
    payload: dict = Field(default_factory=dict)
    sanitized: bool = False
    captured_at: str | None = None
    client_msg_id: str | None = None


class IngestBatch(BaseModel):
    hostname: str
    os: str = ""
    agent_version: str = ""
    ip: str = ""
    events: list[EventItem] = Field(default_factory=list)


class FeatureUpdate(BaseModel):
    enabled: bool | None = None
    config: dict | None = None


class SetupSmtp(BaseModel):
    provider: str = "custom"  # hostinger | office365 | gmail | hotmail | custom | none
    email: str = ""
    password: str = ""
    recipient: str = ""
    host: str = ""
    port: int | None = None
    encryption: str = "starttls"  # starttls | ssl | none


class SetupRequest(BaseModel):
    company_name: str = Field(min_length=1, max_length=100)
    server_host: str = Field(min_length=1, max_length=255)
    admin_username: str = Field(min_length=3, max_length=40)
    admin_password: str = Field(min_length=8, max_length=128)
    branding: dict = Field(default_factory=dict)
    smtp: SetupSmtp | None = None


class LoginRequest(BaseModel):
    username: str
    password: str


class UserCreate(BaseModel):
    username: str = Field(min_length=3, max_length=40)
    password: str = Field(min_length=8, max_length=128)
    role: str = "monitoring"


class UserUpdate(BaseModel):
    role: str | None = None
    active: bool | None = None
    password: str | None = None


class CommandCreate(BaseModel):
    agent_id: int
    kind: str = Field(pattern="^(reboot|wake|run-script)$")
    payload: dict = Field(default_factory=dict)


class CommandResult(BaseModel):
    hostname: str
    status: str = Field(pattern="^(completed|failed)$")
    output: str = ""
    exit_code: int | None = None


# ---------------------------------------------------------------- lifecycle

@app.on_event("startup")
async def startup():
    await db.connect()
    _alert_task = asyncio.create_task(rules.alert_loop())
    app.state.alert_task = _alert_task
    if config.API_TOKEN_AUTOGENERATED:
        print(
            "\n======================================================"
            "\n  AUTO-GENERATED API TOKEN (no API_TOKEN was configured)"
            "\n  save this now - it is shown only at first startup:"
            f"\n\n      {config.API_TOKEN}\n"
            "\n  copy it into the portal (top-right) and into"
            "\n  Enterprise/agent/agent-config.json (token field)."
            "\n======================================================\n",
            flush=True,
        )


@app.on_event("shutdown")
async def shutdown():
    task = getattr(app.state, "alert_task", None)
    if task is not None:
        task.cancel()
    await db.disconnect()


# ---------------------------------------------------------------- setup

@app.get("/api/setup/status")
async def setup_status():
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    info = {"setup_complete": bool(done)}
    if done:
        for key in ("company_name", "server_host", "branding"):
            val = await pool.fetchval("SELECT value FROM settings WHERE key = $1", key)
            if key == "branding" and val:
                val = json.loads(val)
            info[key] = val
    return info


@app.post("/api/setup")
async def run_setup(payload: SetupRequest, response: Response):
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    if done:
        raise HTTPException(status_code=409, detail="Setup already complete")

    certs.ensure_certs(payload.server_host)

    branding = json.dumps(payload.branding or {})
    for key, value in (
        ("company_name", payload.company_name),
        ("server_host", payload.server_host),
        ("branding", branding),
        ("setup_complete", "1"),
    ):
        await pool.execute(
            "INSERT INTO settings (key, value) VALUES ($1, $2) "
            "ON CONFLICT (key) DO UPDATE SET value = $2",
            key, value,
        )

    smtp = payload.smtp
    if smtp and smtp.email and smtp.provider != "none":
        if smtp.provider == "custom":
            host, port, encryption = smtp.host, smtp.port, smtp.encryption
        else:
            preset = config.SMTP_PROVIDERS.get(smtp.provider)
            if preset is None:
                raise HTTPException(status_code=422, detail=f"Unknown SMTP provider: {smtp.provider}")
            host, port, encryption = preset["host"], preset["port"], preset["encryption"]
        if not host or not port:
            raise HTTPException(status_code=422, detail="SMTP host and port are required")
        if encryption not in ("starttls", "ssl", "none"):
            raise HTTPException(status_code=422, detail="SMTP encryption must be starttls, ssl or none")
        for key, value in (
            ("smtp_host", host),
            ("smtp_port", str(port)),
            ("smtp_user", smtp.email),
            ("smtp_password", smtp.password),
            ("smtp_from", smtp.email),
            ("smtp_to", smtp.recipient or smtp.email),
            ("smtp_encryption", encryption),
        ):
            await pool.execute(
                "INSERT INTO settings (key, value) VALUES ($1, $2) "
                "ON CONFLICT (key) DO UPDATE SET value = $2",
                key, value,
            )

    user = await pool.fetchrow(
        "INSERT INTO users (username, password_hash, role) "
        "VALUES ($1, $2, 'admin') RETURNING id, username, role",
        payload.admin_username, auth.hash_password(payload.admin_password),
    )
    token = auth.issue_session(user["id"])
    response.set_cookie(**auth.secure_cookie(token))
    return {
        "company": payload.company_name,
        "server_host": payload.server_host,
        "admin": dict(user),
    }


# ---------------------------------------------------------------- sessions

@app.post("/api/login")
async def login(payload: LoginRequest, response: Response):
    await require_setup_done()
    pool = await db.connect()
    user = await pool.fetchrow(
        "SELECT id, username, password_hash, role, active FROM users WHERE username = $1",
        payload.username,
    )
    if user is None or not user["active"] or not auth.verify_password(payload.password, user["password_hash"]):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    token = auth.issue_session(user["id"])
    response.set_cookie(**auth.secure_cookie(token))
    return {"username": user["username"], "role": user["role"]}


@app.post("/api/logout")
async def logout(response: Response):
    response.delete_cookie(auth.SESSION_COOKIE)
    return {"ok": True}


@app.get("/api/me")
async def me(user: dict = Depends(require_session)):
    return user


@app.get("/api/bootstrap")
async def bootstrap(user: dict = Depends(require_session)):
    pool = await db.connect()
    info = {"user": user}
    for key in ("company_name", "server_host", "branding"):
        val = await pool.fetchval("SELECT value FROM settings WHERE key = $1", key)
        if key == "branding" and val:
            val = json.loads(val)
        info[key] = val
    info["agent_token_configured"] = bool(config.API_TOKEN)
    if user["role"] == "admin":
        info["agent_token"] = config.API_TOKEN
    return info


# ---------------------------------------------------------------- user management (admin)

def _check_role(value: str) -> None:
    if value not in ROLES:
        raise HTTPException(status_code=422, detail=f"Invalid role: {value}")


@app.get("/api/users", dependencies=[Depends(require_session)])
async def list_users(_: dict = Depends(require_role("admin"))):
    pool = await db.connect()
    rows = await pool.fetch(
        "SELECT id, username, role, active, created_by, created_at "
        "FROM users ORDER BY id"
    )
    return [dict(r) for r in rows]


@app.post("/api/users", dependencies=[Depends(require_session)])
async def create_user(payload: UserCreate, admin: dict = Depends(require_role("admin"))):
    _check_role(payload.role)
    pool = await db.connect()
    try:
        row = await pool.fetchrow(
            "INSERT INTO users (username, password_hash, role, created_by) "
            "VALUES ($1, $2, $3, $4) "
            "RETURNING id, username, role, active, created_at",
            payload.username, auth.hash_password(payload.password), payload.role, admin["id"],
        )
    except asyncpg.exceptions.UniqueViolationError:
        raise HTTPException(status_code=409, detail="Username already exists")
    return dict(row)


@app.put("/api/users/{user_id}", dependencies=[Depends(require_session)])
async def update_user(
    user_id: int, payload: UserUpdate, admin: dict = Depends(require_role("admin"))
):
    if payload.role is not None:
        _check_role(payload.role)
    pool = await db.connect()
    row = await pool.fetchrow("SELECT * FROM users WHERE id = $1", user_id)
    if row is None:
        raise HTTPException(status_code=404, detail="User not found")
    if row["id"] == admin["id"] and payload.active is False:
        raise HTTPException(status_code=400, detail="You cannot disable your own account")

    new_role = payload.role if payload.role is not None else row["role"]
    new_active = payload.active if payload.active is not None else row["active"]
    new_hash = (
        auth.hash_password(payload.password) if payload.password else row["password_hash"]
    )
    await pool.execute(
        "UPDATE users SET role = $2, active = $3, password_hash = $4 WHERE id = $1",
        user_id, new_role, new_active, new_hash,
    )
    return {"ok": True, "id": user_id, "role": new_role, "active": new_active}


# ---------------------------------------------------------------- certs & agent template

@app.get("/api/ca.crt", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def download_ca(_: dict = Depends(require_role("admin", "operation"))):
    path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    if not path.exists():
        raise HTTPException(status_code=404, detail="CA not generated yet")
    return FileResponse(path, media_type="application/x-pem-file", filename="itk-ca.crt")


@app.get("/api/agent-template", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def agent_template(_: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    server_host = await pool.fetchval("SELECT value FROM settings WHERE key = 'server_host'")
    company = await pool.fetchval("SELECT value FROM settings WHERE key = 'company_name'")
    ca_path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    return {
        "company": company,
        "server_host": server_host,
        "agent_token": config.API_TOKEN,
        "ca_cert": ca_path.read_text() if ca_path.exists() else None,
    }


# ---------------------------------------------------------------- agent bundle (P3)

@app.get("/api/agent-bundle", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def agent_bundle(_: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    agent_json = await bundle.build_agent_json(pool)
    ca_path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    ca_present = ca_path.exists()
    msi = bundle.msi_path()
    return {
        "company": agent_json["company"],
        "server_host": (await pool.fetchval("SELECT value FROM settings WHERE key = 'server_host'")),
        "scheme": agent_json["endpoint"].split("://")[0],
        "agent_json": agent_json,
        "ca_cert": ca_path.read_text() if ca_present else None,
        "install_cmd": bundle.build_install_cmd(agent_json, ca_present),
        "msi_available": msi.exists(),
        "msi_size": msi.stat().st_size if msi.exists() else None,
        "msi_filename": bundle.MSI_FILENAME,
        "msi_url": "/api/agent-msi",
    }


@app.get("/api/agent/agent.json", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def download_agent_json(_: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    agent_json = await bundle.build_agent_json(pool)
    return JSONResponse(
        content=agent_json,
        headers={"Content-Disposition": 'attachment; filename="agent.json"'},
    )


@app.get("/api/agent/install.cmd", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def download_install_cmd(_: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    agent_json = await bundle.build_agent_json(pool)
    ca_path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    cmd = bundle.build_install_cmd(agent_json, ca_path.exists())
    return Response(
        content=cmd,
        media_type="text/plain",
        headers={"Content-Disposition": 'attachment; filename="install-agent.cmd"'},
    )


@app.get("/api/agent-msi", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def download_msi(_: dict = Depends(require_role("admin", "operation"))):
    path = bundle.msi_path()
    if not path.exists():
        raise HTTPException(status_code=404, detail="MSI not uploaded yet — CI publishes the generic engine build (P0).")
    return FileResponse(path, media_type="application/octet-stream", filename=bundle.MSI_FILENAME)


# ---------------------------------------------------------------- command channel (P5)

@app.get("/api/commands", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_commands(limit: int = 100):
    pool = await db.connect()
    rows = await pool.fetch(
        "SELECT c.id, a.hostname, c.kind, c.payload, c.status, c.result, "
        "       c.created_at, c.picked_up_at, c.completed_at "
        "FROM commands c JOIN agents a ON a.id = c.agent_id "
        "ORDER BY c.id DESC LIMIT $1",
        limit,
    )
    return [dict(r) for r in rows]


@app.post("/api/commands", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def create_command(payload: CommandCreate, user: dict = Depends(require_role("admin", "operation"))):
    if payload.kind == "run-script" and not config.ALLOW_RUN_SCRIPT:
        raise HTTPException(status_code=403, detail="run-script is disabled (COMMANDS_RUN_SCRIPT_ALLOWED=false)")
    if payload.kind == "run-script":
        script = (payload.payload.get("script") or "").strip()
        if script not in config.RUN_SCRIPT_ALLOWLIST:
            raise HTTPException(
                status_code=403,
                detail=f"Script '{script}' is not in the allowlist ({', '.join(config.RUN_SCRIPT_ALLOWLIST) or 'empty'})",
            )
    pool = await db.connect()
    agent = await pool.fetchrow("SELECT id FROM agents WHERE id = $1", payload.agent_id)
    if agent is None:
        raise HTTPException(status_code=404, detail="Agent not found")
    row = await pool.fetchrow(
        "INSERT INTO commands (agent_id, kind, payload, created_by) "
        "VALUES ($1, $2, $3, $4) RETURNING id, agent_id, kind, payload, status, created_at",
        payload.agent_id, payload.kind, payload.payload, user["id"],
    )
    return dict(row)


@app.get("/api/commands/poll", dependencies=[Depends(require_token)])
async def poll_commands(hostname: str, request: Request):
    """Agent-facing: return pending commands for this host (bearer token auth).
    Marks them picked_up so the portal shows they were delivered."""
    pool = await db.connect()
    agent = await pool.fetchrow("SELECT id FROM agents WHERE hostname = $1", hostname)
    if agent is None:
        return []
    rows = await pool.fetch(
        "SELECT id, kind, payload FROM commands "
        "WHERE agent_id = $1 AND status IN ('pending', 'picked_up') "
        "  AND (picked_up_at IS NULL OR picked_up_at > now() - interval '5 minutes') "
        "ORDER BY id ASC LIMIT 10",
        agent["id"],
    )
    for r in rows:
        await pool.execute(
            "UPDATE commands SET status = 'picked_up', picked_up_at = now() WHERE id = $1",
            r["id"],
        )
    return [dict(r) for r in rows]


@app.post("/api/commands/{command_id}/result", dependencies=[Depends(require_token)])
async def command_result(command_id: int, result: CommandResult):
    pool = await db.connect()
    agent = await pool.fetchrow("SELECT id FROM agents WHERE hostname = $1", result.hostname)
    if agent is None:
        raise HTTPException(status_code=404, detail="Agent not found")
    updated = await pool.execute(
        "UPDATE commands SET status = $2, result = $3, completed_at = now() "
        "WHERE id = $1 AND agent_id = $4",
        command_id, result.status,
        {"output": result.output, "exit_code": result.exit_code}, agent["id"],
    )
    if updated == "UPDATE 0":
        raise HTTPException(status_code=404, detail="Command not found for this agent")
    return {"ok": True, "id": command_id, "status": result.status}


# ---------------------------------------------------------------- alerts (P6)

class RuleUpdate(BaseModel):
    enabled: bool | None = None
    severity: str | None = None
    condition: dict | None = None


@app.get("/api/alerts", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_alerts(status: str | None = None, limit: int = 100):
    pool = await db.connect()
    sql = (
        "SELECT al.id, a.hostname, al.severity, al.message, al.status, "
        "       al.created_at, al.resolved_at, r.name AS rule "
        "FROM alerts al "
        "LEFT JOIN agents a ON a.id = al.agent_id "
        "LEFT JOIN alert_rules r ON r.id = al.rule_id WHERE 1=1"
    )
    args: list = []
    if status:
        sql += f" AND al.status = ${len(args) + 1}"
        args.append(status)
    sql += f" ORDER BY al.created_at DESC LIMIT ${max(len(args) + 1, 1)}"
    args.append(limit)
    rows = await pool.fetch(sql, *args)
    return [dict(r) for r in rows]


@app.get("/api/alerts/open", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def open_alerts_count():
    pool = await db.connect()
    count = await pool.fetchval("SELECT count(*) FROM alerts WHERE status = 'open'")
    return {"open": count}


@app.post("/api/alerts/{alert_id}/ack", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def ack_alert(alert_id: int, _: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    await pool.execute("UPDATE alerts SET status = 'acknowledged' WHERE id = $1", alert_id)
    return {"ok": True, "id": alert_id}


@app.post("/api/alerts/{alert_id}/resolve", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def resolve_alert(alert_id: int, _: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    await pool.execute(
        "UPDATE alerts SET status = 'resolved', resolved_at = now() WHERE id = $1", alert_id,
    )
    return {"ok": True, "id": alert_id}


@app.get("/api/alert-rules", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_rules():
    await rules.seed_rules(await db.connect())
    pool = await db.connect()
    rows = await pool.fetch("SELECT * FROM alert_rules ORDER BY id")
    return [dict(r) for r in rows]


@app.put("/api/alert-rules/{name}", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def update_rule(name: str, update: RuleUpdate, _: dict = Depends(require_role("admin"))):
    pool = await db.connect()
    row = await pool.fetchrow("SELECT * FROM alert_rules WHERE name = $1", name)
    if row is None:
        raise HTTPException(status_code=404, detail="Rule not found")
    new_enabled = update.enabled if update.enabled is not None else row["enabled"]
    new_severity = update.severity if update.severity else row["severity"]
    new_condition = update.condition if update.condition is not None else row["condition"]
    await pool.execute(
        "UPDATE alert_rules SET enabled = $2, severity = $3, condition = $4 WHERE name = $1",
        name, new_enabled, new_severity, new_condition,
    )
    return {"ok": True, "name": name}


@app.post("/api/alerts/test-email", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def test_alert_email(_: dict = Depends(require_role("admin"))):
    """Send a test alert email using the configured SMTP settings."""
    pool = await db.connect()
    smtp = await rules.get_smtp_settings(pool)
    if not smtp["host"] or not smtp["to"]:
        raise HTTPException(status_code=400, detail="SMTP not configured (add email settings during setup or in .env)")
    sent = await rules._send_alert_email(
        pool,
        [{"severity": "info", "hostname": "test", "message": "SMTP test message from IT-Toolkit"}],
    )
    if not sent:
        raise HTTPException(status_code=502, detail="SMTP send failed — check logs")
    return {"ok": True, "from": smtp["from"], "to": smtp["to"]}


# ---------------------------------------------------------------- reports (P6)

async def _agent_report_rows(pool) -> list[dict]:
    agents = await pool.fetch(
        "SELECT id, hostname, os, agent_version, ip, registered_at, last_seen "
        "FROM agents ORDER BY hostname"
    )
    rows = []
    for a in agents:
        row = dict(a)
        for kind in ("hardware", "health", "updatecompliance", "diskhealth"):
            p = await pool.fetchrow(
                "SELECT payload, captured_at FROM events WHERE agent_id = $1 AND kind = $2 "
                "ORDER BY captured_at DESC LIMIT 1",
                a["id"], kind,
            )
            if p:
                row[kind] = {"payload": p["payload"], "captured_at": p["captured_at"]}
        rows.append(row)
    return rows


def _as_csv(data: list[dict], columns: list[str]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns, extrasaction="ignore")
    writer.writeheader()
    for row in data:
        writer.writerow(row)
    return buf.getvalue()


@app.get("/api/report/fleet", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def fleet_report():
    pool = await db.connect()
    rows = []
    for r in await _agent_report_rows(pool):
        hw = (r.get("hardware") or {}).get("payload") or {}
        hl = (r.get("health") or {}).get("payload") or {}
        rows.append({
            "hostname": r["hostname"],
            "os": r["os"],
            "ip": r["ip"],
            "agent_version": r["agent_version"],
            "last_seen": r["last_seen"],
            "model": hw.get("model", ""),
            "serial": hw.get("serial", ""),
            "cpu": hw.get("cpu", ""),
            "ram_total_gb": hw.get("ram_total_gb", ""),
            "battery_wear_percent": (hw.get("battery") or {}).get("wear_percent", ""),
            "uptime_hours": hl.get("uptime_hours", ""),
            "cpu_percent": hl.get("cpu_percent", ""),
            "memory_percent": hl.get("memory_percent", ""),
            "reboot_pending": hl.get("reboot_pending", ""),
        })
    columns = ["hostname", "os", "ip", "agent_version", "last_seen", "model", "serial",
               "cpu", "ram_total_gb", "battery_wear_percent", "uptime_hours",
               "cpu_percent", "memory_percent", "reboot_pending"]
    csv_text = _as_csv(rows, columns)
    return Response(
        content=csv_text,
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="fleet-report.csv"'},
    )


@app.get("/api/report/agent/{agent_id}", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def agent_report(agent_id: int, format: str = "json"):
    pool = await db.connect()
    agent = await pool.fetchrow("SELECT * FROM agents WHERE id = $1", agent_id)
    if agent is None:
        raise HTTPException(status_code=404, detail="Agent not found")
    events = await pool.fetch(
        "SELECT id, kind, payload, sanitized, captured_at FROM events "
        "WHERE agent_id = $1 ORDER BY captured_at DESC",
        agent_id,
    )
    if format == "csv":
        rows = [{
            "id": e["id"], "kind": e["kind"], "sanitized": e["sanitized"],
            "captured_at": e["captured_at"], "payload": json.dumps(e["payload"]),
        } for e in events]
        csv_text = _as_csv(rows, ["id", "kind", "sanitized", "captured_at", "payload"])
        return Response(
            content=csv_text,
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="agent-{agent_id}-report.csv"'},
        )
    return {"agent": dict(agent), "event_count": len(events), "events": [dict(e) for e in events]}


# ---------------------------------------------------------------- ingest

@app.post("/ingest")
async def ingest(batch: IngestBatch, request: Request, _: None = Depends(require_token)):
    pool = await db.connect()
    agent_id = await get_agent_id(pool, batch.hostname)
    await pool.execute(
        "UPDATE agents SET os = $2, agent_version = $3, ip = $4 WHERE id = $1",
        agent_id, batch.os, batch.agent_version, batch.ip,
    )

    count = 0
    for ev in batch.events:
        msg_id = ev.client_msg_id or str(uuid.uuid4())
        try:
            row = await pool.fetchrow(
                "INSERT INTO events (agent_id, kind, payload, sanitized, client_msg_id, captured_at) "
                "VALUES ($1, $2, $3, $4, $5, COALESCE(($6::text)::timestamptz, now())) "
                "ON CONFLICT (client_msg_id) DO NOTHING RETURNING id",
                agent_id, ev.kind, ev.payload, ev.sanitized, msg_id, ev.captured_at,
            )
            if row:
                count += 1
        except Exception as exc:
            request.app.state.last_ingest_error = repr(exc)
            continue

    return {"accepted": count, "agent_id": agent_id}


# ---------------------------------------------------------------- admin API

@app.get("/api/agents", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_agents():
    pool = await db.connect()
    rows = await pool.fetch(
        "SELECT id, hostname, os, agent_version, ip, registered_at, last_seen "
        "FROM agents ORDER BY last_seen DESC"
    )
    return [dict(r) for r in rows]


@app.get("/api/events", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_events(agent: str | None = None, kind: str | None = None, limit: int = 100):
    pool = await db.connect()
    sql = (
        "SELECT e.id, e.kind, e.payload, e.sanitized, e.captured_at, a.hostname "
        "FROM events e JOIN agents a ON a.id = e.agent_id WHERE 1=1"
    )
    args: list = []
    if agent:
        sql += " AND a.hostname = $1"
        args.append(agent)
    if kind:
        sql += f" AND e.kind = ${len(args) + 1}"
        args.append(kind)
    sql += f" ORDER BY e.captured_at DESC LIMIT ${max(len(args) + 1, 1)}"
    args.append(limit)
    rows = await pool.fetch(sql, *args)
    return [dict(r) for r in rows]


@app.get("/api/features", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_features():
    pool = await db.connect()
    with open(config.FEATURES_FILE, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)["features"]

    overrides = {r["name"]: r for r in await pool.fetch("SELECT * FROM feature_configs")}
    result = []
    for feat in manifest:
        row = overrides.get(feat["name"])
        result.append({
            "name": feat["name"],
            "label": feat["label"],
            "script": feat["script"],
            "description": feat["description"],
            "enabled": row["enabled"] if row else feat.get("default_enabled", True),
            "config": row["config"] if row else {},
        })
    return result


@app.put("/api/features/{name}", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def update_feature(name: str, update: FeatureUpdate, _: dict = Depends(require_role("admin", "operation"))):
    pool = await db.connect()
    row = await pool.fetchrow("SELECT * FROM feature_configs WHERE name = $1", name)
    if row:
        new_enabled = update.enabled if update.enabled is not None else row["enabled"]
        new_config = update.config if update.config is not None else row["config"]
        await pool.execute(
            "UPDATE feature_configs SET enabled = $2, config = $3, updated_at = now() WHERE name = $1",
            name, new_enabled, new_config,
        )
    else:
        new_enabled = update.enabled if update.enabled is not None else True
        new_config = update.config if update.config is not None else {}
        await pool.execute(
            "INSERT INTO feature_configs (name, enabled, config) VALUES ($1, $2, $3)",
            name, new_enabled, new_config,
        )
    return {"name": name, "enabled": new_enabled, "config": new_config}


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}


@app.get("/api/status", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def api_status(request: Request):
    return {"last_ingest_error": getattr(request.app.state, "last_ingest_error", None)}


# ---------------------------------------------------------------- portal

@app.get("/", include_in_schema=False)
async def portal_index():
    return FileResponse(Path(config.PORTAL_DIR) / "index.html")


app.mount("/static", StaticFiles(directory=config.PORTAL_DIR), name="static")
