import hashlib
import hmac
import json
import secrets
import uuid
from pathlib import Path

from fastapi import FastAPI, Depends, Header, HTTPException, Request, Response
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import auth, certs, config, db

app = FastAPI(title="IT-Toolkit Enterprise", version="1.0.0")


# ---------------------------------------------------------------- deps

def require_token(authorization: str = Header(default="")) -> None:
    """Agent bearer token (used by /ingest)."""
    expected = f"Bearer {config.API_TOKEN}"
    if not hmac.compare_digest(authorization.strip(), expected):
        raise HTTPException(status_code=401, detail="Invalid or missing token")


async def require_setup_done() -> None:
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    if not done:
        raise HTTPException(status_code=428, detail="Setup required")


async def require_session(request: Request) -> dict:
    token = request.cookies.get(auth.SESSION_COOKIE, "")
    user_id = auth.verify_session(token)
    if user_id is None:
        raise HTTPException(status_code=401, detail="Not logged in")
    pool = await db.connect()
    user = await pool.fetchrow(
        "SELECT id, username, role, active FROM users WHERE id = $1 AND active = TRUE",
        user_id,
    )
    if user is None:
        raise HTTPException(status_code=401, detail="Not logged in")
    return dict(user)


async def get_agent_id(pool, hostname: str) -> int:
    row = await pool.fetchrow(
        "INSERT INTO agents (hostname) VALUES ($1) "
        "ON CONFLICT (hostname) DO UPDATE SET last_seen = now() RETURNING id",
        hostname,
    )
    return row["id"]


# ---------------------------------------------------------------- models

class EventItem(BaseModel):
    kind: str
    payload: dict = Field(default_factory=dict)
    sanitized: bool = False
    captured_at: str | None = None
    client_msg_id: str | None = None


class IngestBatch(BaseModel):
    hostname: str
    os: str = ""
    agent_version: str = ""
    ip: str = ""
    events: list[EventItem] = Field(default_factory=list)


class FeatureUpdate(BaseModel):
    enabled: bool | None = None
    config: dict | None = None


class SetupRequest(BaseModel):
    company_name: str = Field(min_length=1, max_length=100)
    server_host: str = Field(min_length=1, max_length=255)
    admin_username: str = Field(min_length=3, max_length=40)
    admin_password: str = Field(min_length=8, max_length=128)
    branding: dict = Field(default_factory=dict)


class LoginRequest(BaseModel):
    username: str
    password: str


# ---------------------------------------------------------------- lifecycle

@app.on_event("startup")
async def startup():
    await db.connect()
    if config.API_TOKEN_AUTOGENERATED:
        print(
            "\n======================================================"
            "\n  AUTO-GENERATED API TOKEN (no API_TOKEN was configured)"
            "\n  save this now - it is shown only at first startup:"
            f"\n\n      {config.API_TOKEN}\n"
            "\n  copy it into the portal (top-right) and into"
            "\n  Enterprise/agent/agent-config.json (token field)."
            "\n======================================================\n",
            flush=True,
        )


@app.on_event("shutdown")
async def shutdown():
    await db.disconnect()


# ---------------------------------------------------------------- setup

@app.get("/api/setup/status")
async def setup_status():
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    info = {"setup_complete": bool(done)}
    if done:
        for key in ("company_name", "server_host", "branding"):
            val = await pool.fetchval("SELECT value FROM settings WHERE key = $1", key)
            if key == "branding" and val:
                val = json.loads(val)
            info[key] = val
    return info


@app.post("/api/setup")
async def run_setup(payload: SetupRequest, response: Response):
    pool = await db.connect()
    done = await pool.fetchval("SELECT value FROM settings WHERE key = 'setup_complete'")
    if done:
        raise HTTPException(status_code=409, detail="Setup already complete")

    certs.ensure_certs(payload.server_host)

    branding = json.dumps(payload.branding or {})
    for key, value in (
        ("company_name", payload.company_name),
        ("server_host", payload.server_host),
        ("branding", branding),
        ("setup_complete", "1"),
    ):
        await pool.execute(
            "INSERT INTO settings (key, value) VALUES ($1, $2) "
            "ON CONFLICT (key) DO UPDATE SET value = $2",
            key, value,
        )

    user = await pool.fetchrow(
        "INSERT INTO users (username, password_hash, role) "
        "VALUES ($1, $2, 'admin') RETURNING id, username, role",
        payload.admin_username, auth.hash_password(payload.admin_password),
    )
    token = auth.issue_session(user["id"])
    response.set_cookie(**auth.secure_cookie(token))
    return {
        "company": payload.company_name,
        "server_host": payload.server_host,
        "admin": dict(user),
    }


# ---------------------------------------------------------------- sessions

@app.post("/api/login")
async def login(payload: LoginRequest, response: Response):
    await require_setup_done()
    pool = await db.connect()
    user = await pool.fetchrow(
        "SELECT id, username, password_hash, role, active FROM users WHERE username = $1",
        payload.username,
    )
    if user is None or not user["active"] or not auth.verify_password(payload.password, user["password_hash"]):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    token = auth.issue_session(user["id"])
    response.set_cookie(**auth.secure_cookie(token))
    return {"username": user["username"], "role": user["role"]}


@app.post("/api/logout")
async def logout(response: Response):
    response.delete_cookie(auth.SESSION_COOKIE)
    return {"ok": True}


@app.get("/api/me")
async def me(user: dict = Depends(require_session)):
    return user


@app.get("/api/bootstrap")
async def bootstrap(user: dict = Depends(require_session)):
    pool = await db.connect()
    info = {"user": user}
    for key in ("company_name", "server_host", "branding"):
        val = await pool.fetchval("SELECT value FROM settings WHERE key = $1", key)
        if key == "branding" and val:
            val = json.loads(val)
        info[key] = val
    info["agent_token_configured"] = bool(config.API_TOKEN)
    if user["role"] == "admin":
        info["agent_token"] = config.API_TOKEN
    return info


# ---------------------------------------------------------------- certs & agent template

@app.get("/api/ca.crt", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def download_ca():
    path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    if not path.exists():
        raise HTTPException(status_code=404, detail="CA not generated yet")
    return FileResponse(path, media_type="application/x-pem-file", filename="itk-ca.crt")


@app.get("/api/agent-template", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def agent_template(user: dict = Depends(require_session)):
    pool = await db.connect()
    server_host = await pool.fetchval("SELECT value FROM settings WHERE key = 'server_host'")
    company = await pool.fetchval("SELECT value FROM settings WHERE key = 'company_name'")
    ca_path = Path(config.DATA_DIR) / "certs" / "ca.crt"
    return {
        "company": company,
        "server_host": server_host,
        "agent_token": config.API_TOKEN,
        "ca_cert": ca_path.read_text() if ca_path.exists() else None,
    }


# ---------------------------------------------------------------- ingest

@app.post("/ingest")
async def ingest(batch: IngestBatch, request: Request, _: None = Depends(require_token)):
    pool = await db.connect()
    agent_id = await get_agent_id(pool, batch.hostname)
    await pool.execute(
        "UPDATE agents SET os = $2, agent_version = $3, ip = $4 WHERE id = $1",
        agent_id, batch.os, batch.agent_version, batch.ip,
    )

    count = 0
    for ev in batch.events:
        msg_id = ev.client_msg_id or str(uuid.uuid4())
        try:
            row = await pool.fetchrow(
                "INSERT INTO events (agent_id, kind, payload, sanitized, client_msg_id, captured_at) "
                "VALUES ($1, $2, $3, $4, $5, COALESCE(($6::text)::timestamptz, now())) "
                "ON CONFLICT (client_msg_id) DO NOTHING RETURNING id",
                agent_id, ev.kind, ev.payload, ev.sanitized, msg_id, ev.captured_at,
            )
            if row:
                count += 1
        except Exception as exc:
            request.app.state.last_ingest_error = repr(exc)
            continue

    return {"accepted": count, "agent_id": agent_id}


# ---------------------------------------------------------------- admin API

@app.get("/api/agents", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_agents():
    pool = await db.connect()
    rows = await pool.fetch(
        "SELECT id, hostname, os, agent_version, ip, registered_at, last_seen "
        "FROM agents ORDER BY last_seen DESC"
    )
    return [dict(r) for r in rows]


@app.get("/api/events", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_events(agent: str | None = None, kind: str | None = None, limit: int = 100):
    pool = await db.connect()
    sql = (
        "SELECT e.id, e.kind, e.payload, e.sanitized, e.captured_at, a.hostname "
        "FROM events e JOIN agents a ON a.id = e.agent_id WHERE 1=1"
    )
    args: list = []
    if agent:
        sql += " AND a.hostname = $1"
        args.append(agent)
    if kind:
        sql += f" AND e.kind = ${len(args) + 1}"
        args.append(kind)
    sql += f" ORDER BY e.captured_at DESC LIMIT ${max(len(args) + 1, 1)}"
    args.append(limit)
    rows = await pool.fetch(sql, *args)
    return [dict(r) for r in rows]


@app.get("/api/features", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def list_features():
    pool = await db.connect()
    with open(config.FEATURES_FILE, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)["features"]

    overrides = {r["name"]: r for r in await pool.fetch("SELECT * FROM feature_configs")}
    result = []
    for feat in manifest:
        row = overrides.get(feat["name"])
        result.append({
            "name": feat["name"],
            "label": feat["label"],
            "script": feat["script"],
            "description": feat["description"],
            "enabled": row["enabled"] if row else feat.get("default_enabled", True),
            "config": row["config"] if row else {},
        })
    return result


@app.put("/api/features/{name}", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def update_feature(name: str, update: FeatureUpdate):
    pool = await db.connect()
    row = await pool.fetchrow("SELECT * FROM feature_configs WHERE name = $1", name)
    if row:
        new_enabled = update.enabled if update.enabled is not None else row["enabled"]
        new_config = update.config if update.config is not None else row["config"]
        await pool.execute(
            "UPDATE feature_configs SET enabled = $2, config = $3, updated_at = now() WHERE name = $1",
            name, new_enabled, new_config,
        )
    else:
        new_enabled = update.enabled if update.enabled is not None else True
        new_config = update.config if update.config is not None else {}
        await pool.execute(
            "INSERT INTO feature_configs (name, enabled, config) VALUES ($1, $2, $3)",
            name, new_enabled, new_config,
        )
    return {"name": name, "enabled": new_enabled, "config": new_config}


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}


@app.get("/api/status", dependencies=[Depends(require_setup_done), Depends(require_session)])
async def api_status(request: Request):
    return {"last_ingest_error": getattr(request.app.state, "last_ingest_error", None)}


# ---------------------------------------------------------------- portal

@app.get("/", include_in_schema=False)
async def portal_index():
    return FileResponse(Path(config.PORTAL_DIR) / "index.html")


app.mount("/static", StaticFiles(directory=config.PORTAL_DIR), name="static")
